version: "3.7"
services:
  app:
    build:
      args:
        user: bani
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: boxbilling
    container_name: boxbilling-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - boxbilling

  db:
    image: mysql:5.7
    container_name: boxbilling-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - boxbilling

  nginx:
    image: nginx:alpine
    container_name: boxbilling-nginx
    restart: unless-stopped
    ports:
      - ${APPLICATION_PORT}:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - boxbilling

networks:
  boxbilling:
    driver: bridge
